// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYWbrW3plZZrQP73v5KNQDWE5YZCtwJxo',
    appId: '1:784219851741:web:9d75a62241663c507b8434',
    messagingSenderId: '784219851741',
    projectId: 'quizzy-login-app',
    authDomain: 'quizzy-login-app.firebaseapp.com',
    storageBucket: 'quizzy-login-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOCEDJeAnq4aadRmOg4mSB7_SX1a92nI',
    appId: '1:784219851741:android:63f0e0cf643778827b8434',
    messagingSenderId: '784219851741',
    projectId: 'quizzy-login-app',
    storageBucket: 'quizzy-login-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgB86ECT6DZDwdrWnobKynprTkV0OtTA',
    appId: '1:784219851741:ios:8aa64b775d78232b7b8434',
    messagingSenderId: '784219851741',
    projectId: 'quizzy-login-app',
    storageBucket: 'quizzy-login-app.appspot.com',
    iosBundleId: 'com.example.quizzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOgB86ECT6DZDwdrWnobKynprTkV0OtTA',
    appId: '1:784219851741:ios:05a530abbf69e6217b8434',
    messagingSenderId: '784219851741',
    projectId: 'quizzy-login-app',
    storageBucket: 'quizzy-login-app.appspot.com',
    iosBundleId: 'com.example.quizzy.RunnerTests',
  );
}
